name: Publish NuGet Package

on:
  push:
    tags:
      - 'v*'

env:
  NUGET_SOURCE: https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Add GitHub Packages source
        run: dotnet nuget add source "$NUGET_SOURCE" --name github --username Hilboard --password ${{ secrets.NUGET_TOKEN }} --store-password-in-clear-text

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release --no-restore

      - name: Create nupkg directory
        run: mkdir -p ./nupkg

      - name: Pack
        run: dotnet pack --configuration Release --no-build -o ./nupkg

      - name: Publish to GitHub Packages
        run: dotnet nuget push ${{ github.workspace }}/nupkg/*.nupkg --source "$NUGET_SOURCE" --api-key ${{ secrets.NUGET_TOKEN }}
